---
- name: Install prerequisites
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - maven
    - openjdk-21-jdk-headless
    - git

- name: Create tests directory
  file:
    path: /tmp/automation_tests
    state: directory
    mode: '0755'

- name: Clone UI tests (Selenoid)
  git:
    repo: "https://{{ github_token | default('') }}@github.com/dimamoryk/AutotestWithSelenoid.git"
    dest: "/tmp/automation_tests/ui-tests"
    version: main
  when: github_token is defined
  ignore_errors: yes

- name: Clone API tests (RestAssured)
  git:
    repo: "https://{{ github_token | default('') }}@github.com/dimamoryk/RestAssuredAutoTest.git"
    dest: "/tmp/automation_tests/api-tests"
    version: main
  when: github_token is defined
  ignore_errors: yes

- name: Clone Mobile tests (Appium)
  git:
    repo: "https://{{ github_token | default('') }}@github.com/dimamoryk/AutoTestWithMobileAppium.git"
    dest: "/tmp/automation_tests/mobile-tests"
    version: main
  when: github_token is defined
  ignore_errors: yes

- name: Run UI tests
  shell: |
    cd /tmp/automation_tests/ui-tests
    mvn clean test
  ignore_errors: yes
  when: "'ui' in test_type or test_type == 'all'"

- name: Run API tests
  shell: |
    cd /tmp/automation_tests/api-tests
    mvn clean test
  ignore_errors: yes
  when: "'api' in test_type or test_type == 'all'"

- name: Run Mobile tests
  shell: |
    cd /tmp/automation_tests/mobile-tests
    mvn clean test
  ignore_errors: yes
  when: "'mobile' in test_type or test_type == 'all'"

