---
- name: Ensure WireMock directory exists
  file:
    path: "{{ wiremock_directory }}"
    state: directory

- name: Copy WireMock mappings
  copy:
    src: "{{ playbook_dir }}/files/stub_mappings/"
    dest: "{{ wiremock_directory }}/mappings"
    remote_src: no

- name: Start WireMock container
  community.docker.docker_container:
    name: wiremock_server
    image: wiremock/wiremock:latest
    restart_policy: always
    published_ports:
      - "{{ wiremock_port }}:8080"
    volumes:
      - "{{ wiremock_directory }}/mappings:/home/wiremock/mappings"
    network_mode: "{{ network_name }}"
    state: started