server {
    listen 80;
    server_name localhost;

    # --- Блок для Jenkins ---
    location /my_jenkins/ {
        proxy_pass http://jenkins:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # --- Блок для Registry ---
    location /v2/ {
        proxy_pass http://registry:5005/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # --- Блок для Selenoid UI ---
    location / {
        proxy_pass http://selenoid-ui:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_buffering off;
    }

    location ~ ^/(static|status|events|logs|vnc)/ {
        proxy_pass http://selenoid-ui:8080$request_uri;
    }
}